# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Searching for Solar Axions with BabyIAXO
author: <a href="https://github.com/lobis">Luis Antonio Obis Aparicio</a>
email: luis.antonio.obis@gmail.com

# Currently we do not include any notebook, this might change
exclude_patterns: [_build, "**.ipynb_checkpoints"]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_engine: xelatex
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/lobis/thesis # Online location of your book
  path_to_book: book # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  favicon: images/logos/favicon.ico
  google_analytics_id: G-F0G4DRBFLP
  extra_navbar: ""

bibtex_bibfiles:
  - bibliography/iaxo.bib
  - bibliography/cosmic.bib
  - bibliography/computing.bib

sphinx:
  config:
    language: en
    bibtex_reference_style: author_year
    html_show_copyright: false
